#!/bin/bash
# Auto-generated by aoi_prepare_experiment.py from your config
export EXPID="TESNorthERA510PCT"
export EXP_ROOT="/projects/hpcl-cli185/proj-shared/wangd/uELM_TES_experiment/TESNorthERA510PCT"
export AOI_POINTS_DIR="/projects/hpcl-cli185/proj-shared/wangd/uELM_TES_experiment"
export AOI_POINTS_FILE="TESNorthERA510PCT_gridID.nc"
export TES_DATA_GROUP_ID="TES_NORTHERA5"
export BASE_DOMAIN_FILE="/projects/hpcl-cli185/proj-shared/wangd/kiloCraft/TES_cases_data/Daymet_ERA5_TESSFA_NORTH/entire_domain/domain_surfdata/NORTHERA5_domain.lnd.TES_NORTHERA5.4km.1d.c251009.nc"
export SURFDATA_DIR="/projects/hpcl-cli185/proj-shared/wangd/kiloCraft/TES_cases_data/Daymet_ERA5_TESSFA_NORTH/entire_domain/domain_surfdata"
export SURFDATA_FILE="surfdata.TESSFA_DOMAIN1.4km.1d.NALCMS.c260218_yw.nc"
export FORCING_DIR="/projects/hpcl-cli185/proj-shared/wangd/kiloCraft/TES_cases_data/Daymet_ERA5_TESSFA_NORTH/entire_domain/forcing"

export SCHED_ACCOUNT="CLI185"
export SCHED_PARTITION="batch_ccsi"
export SCHED_NODES="1"
export SCHED_TIME="12:00:00"
export SCHED_MEM="400G"
export SCHED_TASKS="4"
export SCHED_BOOTSTRAP="['source /software/baseline/nsp/init/profile', 'source /projects/hpcl-cli185/proj-shared/wangd/kiloCraft/python_test_env/activate_shared_env.sh']"
